version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./mailganer/:/usr/src/app/
    ports:
      - '8000:8000'
    env_file:
      - ./mailganer/.env
    depends_on:
      - db
    restart: on-failure

  db:
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - mailganer/.env
    ports:
      - '5432:5432'

  celery:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    command: celery worker --app=mailganer --loglevel=info
    volumes:
      - ./mailganer/:/usr/src/app
    env_file:
      - ./mailganer/.env
    depends_on:
      - web
      - rabbitmq
    restart: on-failure

  rabbitmq:
    image: rabbitmq:3-management-alpine
    command: rabbitmq-server
    ports:
      - '5672:5672'
      - '15672:15672'

  mailhog:
    image: mailhog/mailhog
    container_name: 'mailhog'
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  postgres_data: