# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-24 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='last name')),
                ('first_name', models.CharField(max_length=50, verbose_name='first name')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='middle name')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='birth day')),
            ],
            options={
                'ordering': ('email',),
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='ContactList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('contact', models.ManyToManyField(related_name='lists', to='dashboard.Contact')),
            ],
            options={
                'ordering': ('-created_at', 'name'),
                'verbose_name': 'contact list',
                'verbose_name_plural': 'contacts lists',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('sent', models.IntegerField(blank=True, default=0, editable=False)),
                ('task', models.UUIDField(blank=True, editable=False, null=True)),
                ('contact_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.ContactList')),
            ],
            options={
                'ordering': ('-created_at',),
                'verbose_name': 'mailing',
                'verbose_name_plural': 'mailings',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('subject', models.CharField(max_length=250, verbose_name='subject')),
                ('body', models.TextField(verbose_name='body')),
            ],
            options={
                'ordering': ('-created_at',),
                'verbose_name': 'template',
                'verbose_name_plural': 'templates',
            },
        ),
        migrations.CreateModel(
            name='Viewed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Contact')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Mailing')),
            ],
            options={
                'verbose_name': 'viewed',
                'verbose_name_plural': 'viewed',
            },
        ),
        migrations.AddField(
            model_name='mailing',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Template'),
        ),
    ]
