# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-26 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='status',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True),
        ),
    ]
