# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-26 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_mailing_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('-created_at',), 'verbose_name': 'contact', 'verbose_name_plural': 'contacts'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Enter date of birth.', null=True, verbose_name='birthday'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(help_text='Enter e-mail address.', max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(help_text='Enter a first name.', max_length=50, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(blank=True, default='', help_text='Enter a last name.', max_length=50, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='middle_name',
            field=models.CharField(blank=True, default='', help_text='Enter a middle name.', max_length=50, verbose_name='middle name'),
        ),
        migrations.AlterField(
            model_name='contactlist',
            name='name',
            field=models.CharField(help_text='Enter a name for the list.', max_length=50, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='sent',
            field=models.IntegerField(blank=True, default=0, editable=False, verbose_name='number of shipments'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='start',
            field=models.DateTimeField(blank=True, help_text='Select the UTC time to start the mailing.', null=True, verbose_name='Start mailing'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, verbose_name='mailing status'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='task',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='task number'),
        ),
        migrations.AlterField(
            model_name='template',
            name='body',
            field=models.TextField(help_text='Enter the letter body template.', verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(help_text='Enter the template name', max_length=100, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='template',
            name='subject',
            field=models.CharField(help_text='Enter the subject line.', max_length=250, verbose_name='subject'),
        ),
    ]
